name: Publish

on:
  push:
    branches:
      - publish
  pull_request:
    branches:
      - publish

env:
  _EXTENSION_ID: lphcdnekdljjjfhdhpadlglpejbocdem
  EXTENSION_ID: bpfohppedganilogpplkomnjlleijibp
  VERSION: "25.2.18-alpha"  
  ZIP_FILE: extension-25.2.18-alpha.zip

jobs:
  zip:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: |
          npm install
          npm run build

      - name: Copy required files
        run: |
          cp -r manifest.json dist/
          mkdir -p dist/pages && cp -r pages/* dist/pages/
          mkdir -p dist/images && cp -r images/* dist/images/
      
      # Not required while we use the Artifact
      #- name: Zip extension
      #  run: |
      #    zip -r ${{ env.ZIP_FILE }} dist
      #    echo "### Zip: ${{ env.ZIP_FILE }}" >> $GITHUB_STEP_SUMMARY
        
      #- name: Upload Zip artifact
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: extension
      #    path: ${{ env.ZIP_FILE }}
      
      - name: Create Zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ZIP_FILE }}
          path: dist
        run: |
          echo "### Zip: ${{ env.ZIP_FILE }}" >> $GITHUB_STEP_SUMMARY

  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Update README.md
        run: |
          ARTIFACT_URL=$(gh api "/repos/${{ github.repository }}/actions/artifacts" --jq '.artifacts[0].archive_download_url')
          echo "Updating README.md with artifact link..."
          sed -i "s|Download the extension ZIP|[Download the extension ZIP]($ARTIFACT_URL)|" README.md

      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add README.md
          git commit -m "Update README from publish branch"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    # disabled until we have the refresh token
    if: false 
    needs: zip
    runs-on: ubuntu-24.04
    steps:
      - name: Download Zip artifact
        uses: actions/download-artifact@v4
        with:
          name: extension
      - name: Install chrome-webstore-upload-cli
        run: npm install chrome-webstore-upload-cli
      - name: Publish to Chrome Web Store
        run: |
          npx chrome-webstore-upload-cli upload \
            --source extension-${{ env.VERSION }}.zip \
            --extension-id ${{ env.EXTENSION_ID }} \
            --client-id ${{ secrets.CHROME_CLIENT_ID }} \
            --client-secret ${{ secrets.CHROME_CLIENT_SECRET }} \
            --refresh-token ${{ secrets.CHROME_REFRESH_TOKEN }}
        env:
          CHROME_CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
          CHROME_CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
          CHROME_REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}

