name: Publish

on:
  push:
    branches:
      - publish
  pull_request:
    branches:
      - publish

env:
  EXTENSION_ID: bpfohppedganilogpplkomnjlleijibp
  VERSION: "25.2.18-alpha"  
  ZIP_FILE: extension-25.2.18-alpha.zip

jobs:
  zip:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: |
          npm install
          npm run build

      - name: Copy required files
        run: |
          cp -r manifest.json dist/
          mkdir -p dist/pages && cp -r pages/* dist/pages/
          mkdir -p dist/images && cp -r images/* dist/images/

      - name: Zip extension
        run: |
          zip -r ${{ env.ZIP_FILE }} dist
          echo "### Zip: ${{ env.ZIP_FILE }}" >> $GITHUB_STEP_SUMMARY
        # -r: recursive
        # . : all the archive
        # -x: exclusions
        
      - name: Upload Zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: extension
          path: ${{ env.ZIP_FILE }}

  publish:
    # disabled until we have the refresh token
    if: false 
    needs: zip
    runs-on: ubuntu-24.04
    steps:
      - name: Download Zip artifact
        uses: actions/download-artifact@v4
        with:
          name: extension
      - name: Install chrome-webstore-upload-cli
        run: npm install chrome-webstore-upload-cli
      - name: Publish to Chrome Web Store
        run: |
          npx chrome-webstore-upload-cli upload \
            --source extension-${{ env.VERSION }}.zip \
            --extension-id ${{ env.EXTENSION_ID }} \
            --client-id ${{ secrets.CHROME_CLIENT_ID }} \
            --client-secret ${{ secrets.CHROME_CLIENT_SECRET }} \
            --refresh-token ${{ secrets.CHROME_REFRESH_TOKEN }}
        env:
          CHROME_CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
          CHROME_CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
          CHROME_REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}

